CREATE DATABASE RPA_TRAINING;
USE RPA_TRAINING;

CREATE TABLE ERROR_DETAILS (ERROR_MESSAGE_DETAILS VARCHAR(MAX));
go

CREATE PROCEDURE SP_ADD_ERRORS 
     @errorMessage VARCHAR(MAX)
AS
BEGIN
     INSERT INTO ERROR_DETAILS (ERROR_MESSAGE_DETAILS) VALUES (@errorMessage);
END;

SELECT * FROM ERROR_DETAILS;